apiVersion: v1
kind: Secret
metadata:
  name: cybernet-secrets
  namespace: cybernet-lab
type: Opaque
stringData:
  db-user: "postgres"
  db-password: "CHANGE_ME_POSTGRES_PASSWORD"
  db-name: "cybernet_lab"
  jwt-secret: "CHANGE_ME_JWT_SECRET_64_CHARS_minimum_length_for_production_use"
