export const BACKGROUNDS = [
  { id: 'noc-iceblue', name: 'NOC ICEBLUE', icon: '🖥️', description: 'NOC command center with ice-blue aesthetic' },
  { id: 'global-network', name: 'Global Network', icon: '🌐', description: 'Interactive 3D global network' },
  { id: '3d-globe', name: '3D Globe', icon: '🌍', description: 'Rotating 3D Earth visualization' },
  { id: 'digital-grid', name: 'Digital Grid', icon: '🔲', description: 'Clean digital grid pattern' },
  { id: 'network-galaxy', name: 'Network Galaxy', icon: '🌠', description: 'Cosmic network visualization' },
  { id: 'cyber-grid', name: 'Cyber Grid', icon: '🕸️', description: 'Classic cyber grid with moving lines' },
  { id: 'holographic', name: 'Holographic Network', icon: '📡', description: 'Holographic projection effect' },
  { id: 'data-tunnel', name: 'Data Tunnel', icon: '🌀', description: 'Cyber tunnel perspective' },
  { id: 'wireframe', name: 'Wireframe World', icon: '🔷', description: 'Wireframe 3D world' },
  { id: 'particles', name: 'Particle Network', icon: '✨', description: 'Floating particles with connections' },
  { id: 'soc', name: 'SOC Command', icon: '🛡️', description: 'Security operations center' },
  { id: 'server-room', name: 'Server Room', icon: '🗄️', description: 'Server room visualization' },
  { id: 'digital-sphere', name: 'Digital Sphere', icon: '⚛️', description: 'Floating digital sphere' },
  { id: 'matrix', name: 'Matrix Network', icon: '💚', description: 'Digital matrix rain' },
  { id: 'radar', name: 'Radar Network', icon: '📡', description: 'Radar sweep visualization' },
  { id: 'neural', name: 'Neural Network', icon: '🧠', description: 'Neural network connections' },
  { id: 'quantum', name: 'Quantum Network', icon: '⚛️', description: 'Quantum entanglement effect' },
  { id: 'cyber-city', name: 'Cyber City', icon: '🏙️', description: 'Futuristic cyber city' },
  { id: 'data-center', name: 'Data Center', icon: '💾', description: 'Data center visualization' },
  { id: 'deep-space', name: 'Deep Space Network', icon: '🪐', description: 'Deep space network' },
];