export const BACKGROUNDS = [
  { id: 'noc-iceblue', name: 'NOC ICEBLUE', icon: 'PC', description: 'NOC command center with ice-blue aesthetic' },
  { id: 'global-network', name: 'Global Network', icon: 'Globe', description: 'Interactive 3D global network' },
  { id: '3d-globe', name: '3D Globe', icon: 'Earth', description: 'Rotating 3D Earth visualization' },
  { id: 'digital-grid', name: 'Digital Grid', icon: 'Grid', description: 'Clean digital grid pattern' },
  { id: 'network-galaxy', name: 'Network Galaxy', icon: 'Stars', description: 'Cosmic network visualization' },
  { id: 'cyber-grid', name: 'Cyber Grid', icon: 'Web', description: 'Classic cyber grid with moving lines' },
  { id: 'holographic', name: 'Holographic Network', icon: 'Signal', description: 'Holographic projection effect' },
  { id: 'data-tunnel', name: 'Data Tunnel', icon: 'Spiral', description: 'Cyber tunnel perspective' },
  { id: 'wireframe', name: 'Wireframe World', icon: 'Square', description: 'Wireframe 3D world' },
  { id: 'particles', name: 'Particle Network', icon: 'Sparkle', description: 'Floating particles with connections' },
  { id: 'soc', name: 'SOC Command', icon: 'Shield', description: 'Security operations center' },
  { id: 'server-room', name: 'Server Room', icon: 'Database', description: 'Server room visualization' },
  { id: 'digital-sphere', name: 'Digital Sphere', icon: 'Atom', description: 'Floating digital sphere' },
  { id: 'matrix', name: 'Matrix Network', icon: 'Green', description: 'Digital matrix rain' },
  { id: 'radar', name: 'Radar Network', icon: 'Signal', description: 'Radar sweep visualization' },
  { id: 'neural', name: 'Neural Network', icon: 'Brain', description: 'Neural network connections' },
  { id: 'quantum', name: 'Quantum Network', icon: 'Atom', description: 'Quantum entanglement effect' },
  { id: 'cyber-city', name: 'Cyber City', icon: 'City', description: 'Futuristic cyber city' },
  { id: 'data-center', name: 'Data Center', icon: 'Disk', description: 'Data center visualization' },
  { id: 'deep-space', name: 'Deep Space Network', icon: 'Orbit', description: 'Deep space network' },
];